# docker-compose.yaml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: uz-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: uz
      POSTGRES_PASSWORD: uz
      POSTGRES_DB: uz
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
      - ../docs/sql:/docker-entrypoint-initdb.d
