# docker-compose.yaml
version: '3.8'


services:
  postgres:
    image: postgres:16-alpine
    container_name: uz-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: uz
      POSTGRES_PASSWORD: uz
      POSTGRES_DB: uz
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
      - ../docs/sql:/docker-entrypoint-initdb.d
    network_mode: host
  napcat:
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099
    container_name: napcat
    volumes:
      - ./data/napcat/config:/app/napcat/config
      - ./data/napcat/ntqq:/app/.config/QQ
      - ./data/napcat/koishi:/koishi
    network_mode: host
    restart: always
    image: mlikiowa/napcat-docker:latest
#  koishi:
#    image: koishijs/koishi:latest
#    container_name: koishi
#    ports:
#      - "5140:5140"
#    volumes:
#      - ./data/koishi/koishi:/koishi
#      - ./data/koishi/ntqq:/app/.config/QQ
#    environment:
#      - TZ=Asia/Shanghai
##      - HTTP_PROXY=http://host.docker.internal:7890
##      - HTTPS_PROXY=http://host.docker.internal:7890
##      - http_proxy=http://host.docker.internal:7890
##      - https_proxy=http://host.docker.internal:7890
#    restart: always
#    network_mode: host
#    extra_hosts:
#      - host.docker.internal:host-gateway
##    command: >
##      sh -c "npm install koishi@latest koishi-adapter-onebot@latest && npm start"
